<?php

namespace Tests\Unit;

use App\Models\PricingKeywordRule;
use App\Models\AiAliasMap;
use App\Models\Branch;
use App\Models\GeojsonRegion;
use App\Models\PriceSetting;
use App\Models\RingPricingRule;
use App\Services\JojoBotService;
use App\Services\AiAliasMapService;
use App\Services\PricingKeywordRuleService;
use App\Services\PricingService;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use InvalidArgumentException;
use Tests\TestCase;

class PricingServiceTest extends TestCase
{
    use DatabaseTransactions;

    protected function tearDown(): void
    {
        app(PricingKeywordRuleService::class)->clearCache();

        parent::tearDown();
    }

    public function test_general_pricing_case_one(): void
    {
        $quote = app(PricingService::class)->calculate('ojek', 22, 1);

        $this->assertSame(34800, $quote['tarif']);
        $this->assertSame(1000, $quote['service_charge']);
        $this->assertSame(35800, $quote['total_before_round']);
        $this->assertSame(36000, $quote['final_price']);
    }

    public function test_general_pricing_case_two(): void
    {
        $quote = app(PricingService::class)->calculate('delivery', 8, 3);

        $this->assertSame(12000, $quote['tarif']);
        $this->assertSame(4000, $quote['service_charge']);
        $this->assertSame(16000, $quote['final_price']);
    }

    public function test_general_pricing_case_three(): void
    {
        $quote = app(PricingService::class)->calculate('kurir', 12, 5);

        $this->assertSame(15800, $quote['tarif']);
        $this->assertSame(10000, $quote['service_charge']);
        $this->assertSame(25800, $quote['total_before_round']);
        $this->assertSame(26000, $quote['final_price']);
    }

    public function test_distance_pricing_requires_matching_active_range(): void
    {
        PriceSetting::query()->delete();

        $branch = Branch::query()->create([
            'branch_code' => 'STB-ASB',
            'name' => 'Situbondo',
            'area' => 'Asembagus',
            'latitude' => -7.75086000,
            'longitude' => 114.21561000,
            'radius_km' => 5,
        ]);

        PriceSetting::query()->create([
            'name' => '0-5',
            'branch_id' => $branch->id,
            'min_km' => 0.10,
            'max_km' => 5,
            'price' => 6000,
            'is_formula' => false,
            'per_km_rate' => null,
            'subtract_value' => 0,
            'is_active' => true,
        ]);
        PriceSetting::query()->create([
            'name' => '5-10',
            'branch_id' => $branch->id,
            'min_km' => 5.01,
            'max_km' => 10,
            'price' => 12000,
            'is_formula' => false,
            'per_km_rate' => 1900,
            'subtract_value' => 7000,
            'is_active' => true,
        ]);

        $pricing = app(PricingService::class);

        $this->assertSame(6000, $pricing->calculateTarifFromDatabase(3, $branch->id));
        $this->assertSame(12000, $pricing->calculateTarifFromDatabase(8, $branch->id));

        $this->expectException(\RuntimeException::class);
        $pricing->calculateTarifFromDatabase(12, $branch->id);
    }

    public function test_joker_mobil_distance_rounding_and_tarif(): void
    {
        $quote = app(PricingService::class)->calculate('joker_mobil', 3.6, 1);

        $this->assertSame(4, $quote['billing_distance']);
        $this->assertSame(30000, $quote['tarif']);
        $this->assertSame(30000, $quote['final_price']);
    }

    public function test_travel_route_fixed_price_with_pickup_charge(): void
    {
        $quote = app(PricingService::class)->calculate('travel', 12, 1, 'ASB-JBR');

        $this->assertSame(105000, $quote['route_tarif']);
        $this->assertSame(12000, $quote['pickup_charge']);
        $this->assertSame(117000, $quote['final_price']);
    }

    public function test_invalid_service_type_is_rejected(): void
    {
        $this->expectException(InvalidArgumentException::class);

        app(PricingService::class)->calculate('invalid', 1, 1);
    }

    public function test_special_charge_only_matches_real_keywords(): void
    {
        PricingKeywordRule::query()->delete();
        app(PricingKeywordRuleService::class)->clearCache();
        $pricing = app(PricingService::class);

        $this->assertSame(0, $pricing->extraServiceCharge('Generated by JOJOBOT conversational order dawuhan'));
        $this->assertSame(2000, $pricing->extraServiceCharge('antar ke RS Mitra'));
        $this->assertSame(0, $pricing->extraServiceCharge('tujuan gacoan kota'));
        $this->assertSame(2000, $pricing->extraServiceChargeForService('belanja', 'belikan gacoan'));
        $this->assertSame(3000, $pricing->extraServiceChargeForService('kurir', 'ambil di pasar'));
        $this->assertSame(5000, $pricing->extraServiceChargeForService('gift order', 'gacoan roxy'));
        $this->assertSame(0, $pricing->extraServiceChargeForService('ojek', 'gacoan roxy'));
    }

    public function test_database_keyword_rules_override_hardcoded_fallback(): void
    {
        PricingKeywordRule::query()->delete();
        app(PricingKeywordRuleService::class)->clearCache();
        PricingKeywordRule::query()->create([
            'name' => 'Roxy Custom',
            'keywords' => 'roxy',
            'amount' => 2000,
            'service_scopes' => ['kurir'],
            'is_active' => true,
            'priority' => 10,
        ]);

        $pricing = app(PricingService::class);

        $this->assertSame(2000, $pricing->extraServiceChargeForService('kurir', 'ambil di roxy'));
        $this->assertSame(0, $pricing->extraServiceChargeForService('belanja', 'ambil di roxy'));
        $this->assertSame(0, $pricing->extraServiceChargeForService('kurir', 'antar ke RS Mitra'));
    }

    public function test_master_ring_is_used_for_customer_pricing_when_active(): void
    {
        app(\App\Services\SettingService::class)->set('night_tariff_enabled', false);

        RingPricingRule::query()->create([
            'branch_id' => 1,
            'service_type' => 'ojek',
            'name' => 'Legacy ring terminal',
            'pickup_area' => 'mama marvel',
            'destination_area' => 'terminal',
            'ring' => 'ring_3',
            'price' => 15000,
            'is_bidirectional' => true,
            'source' => 'manual',
            'is_active' => true,
        ]);

        $quote = app(PricingService::class)->calculate([
            'service_type' => 'ojek',
            'branch_id' => 1,
            'pickup_address' => 'mama marvel',
            'pickup_lat' => -7.70924228,
            'pickup_lng' => 113.99408479,
            'destination_address' => 'terminal',
            'destination_lat' => -7.7067986,
            'destination_lng' => 114.0120514,
            'distance_km' => 2,
            'stops' => 1,
        ]);

        $this->assertSame(15000, $quote['tarif']);
        $this->assertSame(16000, $quote['total_price']);
        $this->assertSame('ring_3', $quote['ring']);
        $this->assertArrayHasKey('ring_pricing_rule_id', $quote);
    }

    public function test_master_ring_prefers_lower_ring_when_multiple_rules_match(): void
    {
        app(\App\Services\SettingService::class)->set('night_tariff_enabled', false);
        PriceSetting::query()->delete();
        RingPricingRule::query()->delete();

        $branch = Branch::query()->create([
            'branch_code' => 'STB-KTA-PRIO',
            'name' => 'Situbondo',
            'area' => 'Kota Priority',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        PriceSetting::query()->create([
            'name' => '0-5 priority',
            'branch_id' => $branch->id,
            'min_km' => 0.01,
            'max_km' => 5,
            'price' => 6000,
            'is_formula' => false,
            'is_active' => true,
        ]);

        RingPricingRule::query()->create([
            'branch_id' => $branch->id,
            'service_type' => 'ojek',
            'name' => 'Ring 1 terminal',
            'pickup_area' => 'mama marvel',
            'destination_area' => 'terminal',
            'ring' => 'ring_1',
            'price' => 6000,
            'is_bidirectional' => true,
            'source' => 'manual',
            'is_active' => true,
            'created_at' => now()->subMinute(),
            'updated_at' => now()->subMinute(),
        ]);

        RingPricingRule::query()->create([
            'branch_id' => $branch->id,
            'service_type' => 'ojek',
            'name' => 'Ring 3 terminal newer',
            'pickup_area' => 'mama marvel',
            'destination_area' => 'terminal',
            'ring' => 'ring_3',
            'price' => 15000,
            'is_bidirectional' => true,
            'source' => 'manual',
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $quote = app(PricingService::class)->calculate([
            'service_type' => 'ojek',
            'branch_id' => $branch->id,
            'pickup_address' => 'mama marvel',
            'pickup_lat' => -7.70924228,
            'pickup_lng' => 113.99408479,
            'destination_address' => 'terminal',
            'destination_lat' => -7.7067986,
            'destination_lng' => 114.0120514,
            'distance_km' => 2,
            'stops' => 1,
        ]);

        $this->assertSame(6000, $quote['tarif']);
        $this->assertSame('ring_1', $quote['ring']);
        $this->assertSame(7000, $quote['total_price']);
    }

    public function test_master_ring_polygon_no_longer_controls_customer_pricing(): void
    {
        app(\App\Services\SettingService::class)->set('night_tariff_enabled', false);
        PriceSetting::query()->delete();
        RingPricingRule::query()->delete();

        $branchA = Branch::query()->create([
            'branch_code' => 'PLY-A',
            'name' => 'Polygon',
            'area' => 'A',
            'latitude' => -7.70000000,
            'longitude' => 114.00000000,
            'radius_km' => 5,
        ]);
        $branchB = Branch::query()->create([
            'branch_code' => 'PLY-B',
            'name' => 'Polygon',
            'area' => 'B',
            'latitude' => -7.80000000,
            'longitude' => 114.10000000,
            'radius_km' => 5,
        ]);

        foreach ([$branchA, $branchB] as $branch) {
            PriceSetting::query()->create([
                'name' => '0-5 '.$branch->branch_code,
                'branch_id' => $branch->id,
                'min_km' => 0.01,
                'max_km' => 5,
                'price' => 6000,
                'is_formula' => false,
                'is_active' => true,
            ]);
        }

        RingPricingRule::query()->create([
            'branch_id' => $branchA->id,
            'service_type' => 'ojek',
            'name' => 'Ring polygon A',
            'area_mode' => 'polygon',
            'pickup_area' => 'Cabang A',
            'destination_area' => 'Ring 3 A',
            'polygon_coordinates' => [
                ['lat' => -7.71000000, 'lng' => 113.99000000],
                ['lat' => -7.71000000, 'lng' => 114.03000000],
                ['lat' => -7.68000000, 'lng' => 114.03000000],
                ['lat' => -7.68000000, 'lng' => 113.99000000],
            ],
            'polygon_match_point' => 'destination',
            'ring' => 'ring_3',
            'price' => 15000,
            'is_bidirectional' => true,
            'source' => 'manual',
            'is_active' => true,
        ]);

        $payload = [
            'service_type' => 'ojek',
            'pickup_address' => 'Pickup',
            'pickup_lat' => -7.70900000,
            'pickup_lng' => 114.00100000,
            'destination_address' => 'Tujuan polygon',
            'destination_lat' => -7.69500000,
            'destination_lng' => 114.01000000,
            'distance_km' => 2,
            'stops' => 1,
        ];

        $quoteSameBranch = app(PricingService::class)->calculate([
            ...$payload,
            'branch_id' => $branchA->id,
        ]);
        $quoteOtherBranch = app(PricingService::class)->calculate([
            ...$payload,
            'branch_id' => $branchB->id,
        ]);

        $this->assertSame(6000, $quoteSameBranch['tarif']);
        $this->assertArrayNotHasKey('ring_pricing_rule_id', $quoteSameBranch);
        $this->assertSame(6000, $quoteOtherBranch['tarif']);
        $this->assertArrayNotHasKey('ring_pricing_rule_id', $quoteOtherBranch);
    }

    public function test_master_ring_polygon_accepts_geojson_polygon(): void
    {
        $method = new \ReflectionMethod(\App\Filament\Resources\RingPricingRuleResource::class, 'normalizePolygonCoordinates');
        $method->setAccessible(true);

        $points = $method->invoke(null, json_encode([
            'type' => 'FeatureCollection',
            'features' => [[
                'type' => 'Feature',
                'properties' => [],
                'geometry' => [
                    'type' => 'Polygon',
                    'coordinates' => [[
                        [114.00000001, -7.70000001],
                        [114.02000002, -7.70000002],
                        [114.02000003, -7.68000003],
                        [114.00000004, -7.70000004],
                    ]],
                ],
            ]],
        ]));

        $this->assertCount(4, $points);
        $this->assertSame(['lat' => -7.70000001, 'lng' => 114.00000001], $points[0]);
    }

    public function test_master_ring_polygon_accepts_geojson_linestring_collection(): void
    {
        $method = new \ReflectionMethod(\App\Filament\Resources\RingPricingRuleResource::class, 'normalizePolygonCoordinates');
        $method->setAccessible(true);

        $points = $method->invoke(null, json_encode([
            'type' => 'FeatureCollection',
            'features' => [
                [
                    'type' => 'Feature',
                    'properties' => [],
                    'geometry' => [
                        'type' => 'LineString',
                        'coordinates' => [
                            [112.73158776985912, -7.314985546199608],
                            [112.68721447118088, -7.309396276304284],
                        ],
                    ],
                ],
                [
                    'type' => 'Feature',
                    'properties' => [],
                    'geometry' => [
                        'type' => 'LineString',
                        'coordinates' => [
                            [112.73090272984507, -7.31431724325121],
                            [112.77245348602054, -7.322000206176796],
                        ],
                    ],
                ],
                [
                    'type' => 'Feature',
                    'properties' => [],
                    'geometry' => [
                        'type' => 'LineString',
                        'coordinates' => [
                            [112.72879024735755, -7.316412480549417],
                            [112.7140014046742, -7.357622231804314],
                        ],
                    ],
                ],
            ],
        ]));

        $this->assertGreaterThanOrEqual(3, count($points));
        $this->assertContains(['lat' => -7.32200021, 'lng' => 112.77245349], $points);
    }

    public function test_jojobot_rejects_pricing_geocode_outside_branch_radius(): void
    {
        $branch = new Branch([
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'isGeocodeTooFarFromBranch');
        $method->setAccessible(true);

        $this->assertTrue($method->invoke($service, ['distance_from_bias_km' => 12], $branch));
        $this->assertFalse($method->invoke($service, ['distance_from_bias_km' => 4], $branch));
    }

    public function test_jojobot_prefers_local_rsud_alias_before_generic_geocode(): void
    {
        $branch = new Branch([
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'geocodeCandidates');
        $method->setAccessible(true);

        $candidates = $method->invoke($service, 'depan rsud', $branch);

        $this->assertSame('rsud Situbondo, Indonesia', $candidates[0]);
        $this->assertLessThan(
            array_search('depan rsud', $candidates, true),
            array_search('rsud Situbondo, Indonesia', $candidates, true),
        );
    }

    public function test_jojobot_prefers_local_terminal_alias_before_generic_geocode(): void
    {
        $branch = new Branch([
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'geocodeCandidates');
        $method->setAccessible(true);

        $candidates = $method->invoke($service, 'terminal', $branch);

        $this->assertSame('terminal Situbondo, Indonesia', $candidates[0]);
        $this->assertLessThan(
            array_search('terminal', $candidates, true),
            array_search('terminal Situbondo, Indonesia', $candidates, true),
        );
    }

    public function test_geojson_region_can_be_used_as_pricing_geocode_reference(): void
    {
        $branch = Branch::query()->create([
            'branch_code' => 'STB-GEO',
            'name' => 'Situbondo',
            'area' => 'Kota Geo',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        GeojsonRegion::query()->create([
            'branch_id' => $branch->id,
            'name' => 'Panarukan',
            'geojson' => [
                'type' => 'Feature',
                'properties' => ['name' => 'Panarukan'],
                'geometry' => [
                    'type' => 'Polygon',
                    'coordinates' => [[
                        [114.0800, -7.7100],
                        [114.0820, -7.7100],
                        [114.0820, -7.7080],
                        [114.0800, -7.7080],
                        [114.0800, -7.7100],
                    ]],
                ],
            ],
            'geometry_type' => 'Polygon',
            'coordinates' => [[
                ['lat' => -7.7100, 'lng' => 114.0800],
                ['lat' => -7.7100, 'lng' => 114.0820],
                ['lat' => -7.7080, 'lng' => 114.0820],
                ['lat' => -7.7080, 'lng' => 114.0800],
            ]],
            'centroid_lat' => -7.7090,
            'centroid_lng' => 114.0810,
            'min_lat' => -7.7100,
            'max_lat' => -7.7080,
            'min_lng' => 114.0800,
            'max_lng' => 114.0820,
            'version' => 1,
            'is_active' => true,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'geocodeForPricing');
        $method->setAccessible(true);

        $result = $method->invoke($service, 'ke Panarukan', $branch);

        $this->assertSame('geojson_region', $result['provider']);
        $this->assertSame('Panarukan', $result['geojson_region_name']);
        $this->assertSame(114.0810, $result['lng']);
    }

    public function test_ai_alias_map_resolves_local_alias_to_geojson_region(): void
    {
        $branch = Branch::query()->create([
            'branch_code' => 'STB-ALIAS',
            'name' => 'Situbondo',
            'area' => 'Kota Alias',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $region = GeojsonRegion::query()->create([
            'branch_id' => $branch->id,
            'name' => 'Kelurahan Mimbaan',
            'geojson' => [
                'type' => 'Feature',
                'properties' => ['name' => 'Kelurahan Mimbaan'],
                'geometry' => [
                    'type' => 'Polygon',
                    'coordinates' => [[
                        [114.0500, -7.7100],
                        [114.0520, -7.7100],
                        [114.0520, -7.7080],
                        [114.0500, -7.7080],
                        [114.0500, -7.7100],
                    ]],
                ],
            ],
            'geometry_type' => 'Polygon',
            'coordinates' => [[
                ['lat' => -7.7100, 'lng' => 114.0500],
                ['lat' => -7.7100, 'lng' => 114.0520],
                ['lat' => -7.7080, 'lng' => 114.0520],
                ['lat' => -7.7080, 'lng' => 114.0500],
            ]],
            'centroid_lat' => -7.7090,
            'centroid_lng' => 114.0510,
            'min_lat' => -7.7100,
            'max_lat' => -7.7080,
            'min_lng' => 114.0500,
            'max_lng' => 114.0520,
            'version' => 1,
            'is_active' => true,
        ]);

        AiAliasMap::query()->create([
            'branch_id' => $branch->id,
            'geojson_region_id' => $region->id,
            'canonical_name' => 'Kelurahan Mimbaan',
            'aliases' => ['mimbaan barat', 'dekat mimbaan', 'mimbaan'],
            'source' => 'manual',
            'confidence' => 95,
            'priority' => 20,
            'is_active' => true,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'geocodeForPricing');
        $method->setAccessible(true);

        $result = $method->invoke($service, 'Mimbaan Barat', $branch);

        $this->assertSame('ai_alias_map', $result['provider']);
        $this->assertSame('Kelurahan Mimbaan', $result['ai_alias_canonical_name']);
        $this->assertSame($region->id, $result['geojson_region_id']);
        $this->assertSame(114.0510, $result['lng']);
    }

    public function test_ai_alias_map_does_not_hijack_specific_address_with_branch_name(): void
    {
        $branch = Branch::query()->create([
            'branch_code' => 'STB-CITY',
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $region = GeojsonRegion::query()->create([
            'branch_id' => $branch->id,
            'name' => 'Situbondo',
            'geojson' => ['type' => 'Feature', 'properties' => ['name' => 'Situbondo'], 'geometry' => ['type' => 'Polygon', 'coordinates' => [[[114.0700, -7.7180], [114.0720, -7.7180], [114.0720, -7.7160], [114.0700, -7.7160], [114.0700, -7.7180]]]]],
            'geometry_type' => 'Polygon',
            'coordinates' => [[
                ['lat' => -7.7180, 'lng' => 114.0700],
                ['lat' => -7.7180, 'lng' => 114.0720],
                ['lat' => -7.7160, 'lng' => 114.0720],
                ['lat' => -7.7160, 'lng' => 114.0700],
            ]],
            'centroid_lat' => -7.7170,
            'centroid_lng' => 114.0710,
            'min_lat' => -7.7180,
            'max_lat' => -7.7160,
            'min_lng' => 114.0700,
            'max_lng' => 114.0720,
            'version' => 1,
            'is_active' => true,
        ]);

        AiAliasMap::query()->create([
            'branch_id' => $branch->id,
            'geojson_region_id' => $region->id,
            'canonical_name' => 'Situbondo',
            'aliases' => ['kota', 'situbondo kota', 'terminal situbondo'],
            'source' => 'generated',
            'confidence' => 95,
            'priority' => 20,
            'is_active' => true,
        ]);

        $service = app(AiAliasMapService::class);

        $this->assertSame('Situbondo', $service->resolve('kota', $branch->id)?->canonical_name);
        $this->assertNull($service->resolve('smp 1 situbondo', $branch->id));
    }

    public function test_jojobot_adds_branch_name_candidate_for_free_aliases(): void
    {
        $branch = new Branch([
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'geocodeCandidates');
        $method->setAccessible(true);

        $candidates = $method->invoke($service, 'mama marvel', $branch);

        $this->assertContains('mama marvel Situbondo, Indonesia', $candidates);
        $this->assertLessThan(
            array_search('mama marvel', $candidates, true),
            array_search('mama marvel Situbondo, Indonesia', $candidates, true),
        );
    }

    public function test_night_tariff_rounds_from_order_subtotal(): void
    {
        app(\App\Services\SettingService::class)->set('night_tariff_enabled', true);
        app(\App\Services\SettingService::class)->set('night_tariff_rules', json_encode([
            ['area' => '', 'start' => '00:00', 'end' => '23:59', 'percent' => 30],
        ]));

        $quote = app(PricingService::class)->calculate([
            'service_type' => 'ojek',
            'pickup_address' => 'Pickup',
            'pickup_lat' => -7.70924228,
            'pickup_lng' => 113.99408479,
            'destination_address' => 'Destination',
            'destination_lat' => -7.7067986,
            'destination_lng' => 114.0120514,
            'branch_id' => 1,
            'distance_km' => 2,
            'stops' => 1,
        ]);

        $this->assertSame(6000, $quote['base_tarif_before_night']);
        $this->assertSame(7000, $quote['base_total_before_night']);
        $this->assertSame(3000, $quote['night_tariff_charge']);
        $this->assertSame(9000, $quote['tarif']);
        $this->assertSame(10000, $quote['total_price']);
    }

    public function test_jojobot_ignores_ambiguous_branch_area_hint(): void
    {
        Branch::query()->create([
            'branch_code' => 'STB-KTA',
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);
        Branch::query()->create([
            'branch_code' => 'BWS-KTA',
            'name' => 'Bondowoso',
            'area' => 'Kota',
            'latitude' => -7.91326642,
            'longitude' => 113.82250071,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'branchIdFromText');
        $method->setAccessible(true);

        $this->assertNull($method->invoke($service, 'Kota'));
    }

    public function test_jojobot_menu_keyword_does_not_match_inside_terminal(): void
    {
        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'containsAny');
        $method->setAccessible(true);

        $this->assertFalse($method->invoke($service, 'antar dari mama marvel ke terminal', ['min']));
        $this->assertTrue($method->invoke($service, 'min mau order', ['min']));
    }
}
