<?php

namespace Tests\Unit;

use App\Models\PricingKeywordRule;
use App\Models\Branch;
use App\Services\JojoBotService;
use App\Services\PricingKeywordRuleService;
use App\Services\PricingService;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use InvalidArgumentException;
use Tests\TestCase;

class PricingServiceTest extends TestCase
{
    use DatabaseTransactions;

    protected function tearDown(): void
    {
        app(PricingKeywordRuleService::class)->clearCache();

        parent::tearDown();
    }

    public function test_general_pricing_case_one(): void
    {
        $quote = app(PricingService::class)->calculate('ojek', 22, 1);

        $this->assertSame(34800, $quote['tarif']);
        $this->assertSame(1000, $quote['service_charge']);
        $this->assertSame(35800, $quote['total_before_round']);
        $this->assertSame(36000, $quote['final_price']);
    }

    public function test_general_pricing_case_two(): void
    {
        $quote = app(PricingService::class)->calculate('delivery', 8, 3);

        $this->assertSame(12000, $quote['tarif']);
        $this->assertSame(4000, $quote['service_charge']);
        $this->assertSame(16000, $quote['final_price']);
    }

    public function test_general_pricing_case_three(): void
    {
        $quote = app(PricingService::class)->calculate('kurir', 12, 5);

        $this->assertSame(15800, $quote['tarif']);
        $this->assertSame(10000, $quote['service_charge']);
        $this->assertSame(25800, $quote['total_before_round']);
        $this->assertSame(26000, $quote['final_price']);
    }

    public function test_joker_mobil_distance_rounding_and_tarif(): void
    {
        $quote = app(PricingService::class)->calculate('joker_mobil', 3.6, 1);

        $this->assertSame(4, $quote['billing_distance']);
        $this->assertSame(30000, $quote['tarif']);
        $this->assertSame(30000, $quote['final_price']);
    }

    public function test_travel_route_fixed_price_with_pickup_charge(): void
    {
        $quote = app(PricingService::class)->calculate('travel', 12, 1, 'ASB-JBR');

        $this->assertSame(105000, $quote['route_tarif']);
        $this->assertSame(12000, $quote['pickup_charge']);
        $this->assertSame(117000, $quote['final_price']);
    }

    public function test_invalid_service_type_is_rejected(): void
    {
        $this->expectException(InvalidArgumentException::class);

        app(PricingService::class)->calculate('invalid', 1, 1);
    }

    public function test_special_charge_only_matches_real_keywords(): void
    {
        PricingKeywordRule::query()->delete();
        app(PricingKeywordRuleService::class)->clearCache();
        $pricing = app(PricingService::class);

        $this->assertSame(0, $pricing->extraServiceCharge('Generated by JOJOBOT conversational order dawuhan'));
        $this->assertSame(2000, $pricing->extraServiceCharge('antar ke RS Mitra'));
        $this->assertSame(0, $pricing->extraServiceCharge('tujuan gacoan kota'));
        $this->assertSame(2000, $pricing->extraServiceChargeForService('belanja', 'belikan gacoan'));
        $this->assertSame(3000, $pricing->extraServiceChargeForService('kurir', 'ambil di pasar'));
        $this->assertSame(5000, $pricing->extraServiceChargeForService('gift order', 'gacoan roxy'));
        $this->assertSame(0, $pricing->extraServiceChargeForService('ojek', 'gacoan roxy'));
    }

    public function test_database_keyword_rules_override_hardcoded_fallback(): void
    {
        PricingKeywordRule::query()->delete();
        app(PricingKeywordRuleService::class)->clearCache();
        PricingKeywordRule::query()->create([
            'name' => 'Roxy Custom',
            'keywords' => 'roxy',
            'amount' => 2000,
            'service_scopes' => ['kurir'],
            'is_active' => true,
            'priority' => 10,
        ]);

        $pricing = app(PricingService::class);

        $this->assertSame(2000, $pricing->extraServiceChargeForService('kurir', 'ambil di roxy'));
        $this->assertSame(0, $pricing->extraServiceChargeForService('belanja', 'ambil di roxy'));
        $this->assertSame(0, $pricing->extraServiceChargeForService('kurir', 'antar ke RS Mitra'));
    }

    public function test_jojobot_rejects_pricing_geocode_outside_branch_radius(): void
    {
        $branch = new Branch([
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'isGeocodeTooFarFromBranch');
        $method->setAccessible(true);

        $this->assertTrue($method->invoke($service, ['distance_from_bias_km' => 12], $branch));
        $this->assertFalse($method->invoke($service, ['distance_from_bias_km' => 4], $branch));
    }

    public function test_jojobot_prefers_local_rsud_alias_before_generic_geocode(): void
    {
        $branch = new Branch([
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'geocodeCandidates');
        $method->setAccessible(true);

        $candidates = $method->invoke($service, 'depan rsud', $branch);

        $this->assertSame('rsud Situbondo, Indonesia', $candidates[0]);
        $this->assertLessThan(
            array_search('depan rsud', $candidates, true),
            array_search('rsud Situbondo, Indonesia', $candidates, true),
        );
    }

    public function test_jojobot_ignores_ambiguous_branch_area_hint(): void
    {
        Branch::query()->create([
            'branch_code' => 'STB-KTA',
            'name' => 'Situbondo',
            'area' => 'Kota',
            'latitude' => -7.70924228,
            'longitude' => 113.99408479,
            'radius_km' => 5,
        ]);
        Branch::query()->create([
            'branch_code' => 'BWS-KTA',
            'name' => 'Bondowoso',
            'area' => 'Kota',
            'latitude' => -7.91326642,
            'longitude' => 113.82250071,
            'radius_km' => 5,
        ]);

        $service = app(JojoBotService::class);
        $method = new \ReflectionMethod($service, 'branchIdFromText');
        $method->setAccessible(true);

        $this->assertNull($method->invoke($service, 'Kota'));
    }
}
